package main

import (
	"log"
	"net/http"

	_ "cwt/docs" // Swagger docs (generated by swag command)
	"cwt/internal/api"
	"cwt/internal/config"
)

// @title           Local Crypto Wallet Service API
// @version         1.0
// @description     Local Go service for generating crypto wallets, viewing balance and sending stablecoins
// @termsOfService  http://swagger.io/terms/

// @host      127.0.0.1:8080
// @BasePath  /

// @schemes http

func main() {
	// Initialize configuration from environment variables
	if err := config.Init(); err != nil {
		log.Fatalf("Failed to initialize config: %v", err)
	}

	// Setup router
	handler, err := api.SetupRouter()
	if err != nil {
		log.Fatalf("Failed to setup router: %v", err)
	}

	// Start server on localhost only (local wallet security)
	addr := "127.0.0.1:" + config.GetPort()
	log.Printf("Server starting on %s", addr)

	server := &http.Server{
		Addr:    addr,
		Handler: handler,
	}

	if err := server.ListenAndServe(); err != nil {
		log.Fatalf("Failed to start server: %v", err)
	}
}
