package main

import (
	"context"
	"log"
	"net/http"
	"os"
	"os/signal"
	"syscall"
	"time"

	_ "github.com/AlexZinkM/local-wallet/docs" // Swagger docs (generated by swag command)
	"github.com/AlexZinkM/local-wallet/internal/api"
	"github.com/AlexZinkM/local-wallet/internal/config"
)

// @title           Local Crypto Wallet Service API
// @version         1.0
// @description     Local Go service for generating crypto wallets, viewing balance and sending stablecoins
// @termsOfService  http://swagger.io/terms/

// @host      127.0.0.1:8080
// @BasePath  /

// @schemes http

func main() {
	// Initialize configuration from environment variables
	if err := config.Init(); err != nil {
		log.Fatalf("Failed to initialize config: %v", err)
	}

	// Prompt for wallet password at runtime (stored securely in memory)
	if err := config.PromptForPassword(); err != nil {
		log.Fatalf("Failed to get password: %v", err)
	}

	// Setup router
	handler, err := api.SetupRouter()
	if err != nil {
		log.Fatalf("Failed to setup router: %v", err)
	}

	// Start server on localhost only (local wallet security)
	addr := "127.0.0.1:" + config.GetPort()
	log.Printf("Server starting on %s", addr)

	server := &http.Server{
		Addr:    addr,
		Handler: handler,
	}

	// Run server in goroutine so we can handle shutdown signals
	go func() {
		if err := server.ListenAndServe(); err != nil && err != http.ErrServerClosed {
			log.Fatalf("Server error: %v", err)
		}
	}()

	// Wait for interrupt signal (Ctrl+C or SIGTERM)
	quit := make(chan os.Signal, 1)
	signal.Notify(quit, syscall.SIGINT, syscall.SIGTERM)
	<-quit

	log.Printf("Shutting down server...")
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()

	if err := server.Shutdown(ctx); err != nil {
		log.Fatalf("Server forced to shutdown: %v", err)
	}
	log.Printf("Server stopped")
}
